// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: log.sql

package queries

import (
	"context"
)

const createLogTable = `-- name: CreateLogTable :exec
CREATE TABLE IF NOT EXISTS log (
    id SERIAL PRIMARY KEY,
    level TEXT NOT NULL,              
    message TEXT NOT NULL,          
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Log timestamp
)
`

func (q *Queries) CreateLogTable(ctx context.Context) error {
	_, err := q.exec(ctx, q.createLogTableStmt, createLogTable)
	return err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO log (level, message) VALUES (?, ?)
`

type InsertLogParams struct {
	Level   string `json:"level"`
	Message string `json:"message"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.exec(ctx, q.insertLogStmt, insertLog, arg.Level, arg.Message)
	return err
}
