// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type Log struct {
	ID        interface{}  `json:"id"`
	Level     string       `json:"level"`
	Message   string       `json:"message"`
	CreatedAt sql.NullTime `json:"created_at"`
}
