// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// DriverMock is an autogenerated mock type for the Driver type
type DriverMock struct {
	mock.Mock
}

type DriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverMock) EXPECT() *DriverMock_Expecter {
	return &DriverMock_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields:
func (_m *DriverMock) Begin() (*sql.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DriverMock_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type DriverMock_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *DriverMock_Expecter) Begin() *DriverMock_Begin_Call {
	return &DriverMock_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *DriverMock_Begin_Call) Run(run func()) *DriverMock_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverMock_Begin_Call) Return(_a0 *sql.Tx, _a1 error) *DriverMock_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DriverMock_Begin_Call) RunAndReturn(run func() (*sql.Tx, error)) *DriverMock_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *DriverMock) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DriverMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DriverMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DriverMock_Expecter) Close() *DriverMock_Close_Call {
	return &DriverMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DriverMock_Close_Call) Run(run func()) *DriverMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverMock_Close_Call) Return(_a0 error) *DriverMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DriverMock_Close_Call) RunAndReturn(run func() error) *DriverMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *DriverMock) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DriverMock_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type DriverMock_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *DriverMock_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *DriverMock_ExecContext_Call {
	return &DriverMock_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *DriverMock_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *DriverMock_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DriverMock_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *DriverMock_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DriverMock_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (sql.Result, error)) *DriverMock_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function with given fields: ctx, query
func (_m *DriverMock) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DriverMock_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type DriverMock_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *DriverMock_Expecter) PrepareContext(ctx interface{}, query interface{}) *DriverMock_PrepareContext_Call {
	return &DriverMock_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *DriverMock_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *DriverMock_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DriverMock_PrepareContext_Call) Return(_a0 *sql.Stmt, _a1 error) *DriverMock_PrepareContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DriverMock_PrepareContext_Call) RunAndReturn(run func(context.Context, string) (*sql.Stmt, error)) *DriverMock_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *DriverMock) QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (*sql.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DriverMock_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type DriverMock_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *DriverMock_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *DriverMock_QueryContext_Call {
	return &DriverMock_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *DriverMock_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *DriverMock_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DriverMock_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *DriverMock_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DriverMock_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (*sql.Rows, error)) *DriverMock_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, query, args
func (_m *DriverMock) QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// DriverMock_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type DriverMock_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *DriverMock_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *DriverMock_QueryRowContext_Call {
	return &DriverMock_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *DriverMock_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *DriverMock_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DriverMock_QueryRowContext_Call) Return(_a0 *sql.Row) *DriverMock_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DriverMock_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) *sql.Row) *DriverMock_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewDriverMock creates a new instance of DriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverMock {
	mock := &DriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
