with-expecter: True
filename: "{{ .InterfaceName | snakecase }}_mock.go"
mockname: "{{ .InterfaceName }}Mock"
dir: "./database/mocks"
outpkg: "mocks"
packages:
  github.com/lucasvillarinho/litepack/database/drivers:
    interfaces:            
      Driver:                
        config:
          recursive: false
  github.com/lucasvillarinho/litepack/database:
    interfaces:
      Database:
        config:
          recursive: false